backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "online-worship" # Used in routes, e.g., /admin/collections/blog
    label: "オンライン礼拝" # Used in the UI
    folder: "content/online-worship" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}_{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: online-worship/{{slug}}
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "online-giving" # Used in routes, e.g., /admin/collections/blog
    label: "オンライン献金" # Used in the UI
    folder: "content/online-giving" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}_{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: online-giving/{{slug}}
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Icon", name: "icon", widget: "string", required: false, hint: "トップページ用"}
      - {label: "Description", name: "description", widget: "string", required: false, hint: "トップページ用"}
      - {label: "Weight", name: "weight", widget: "number", step: 1, required: false, hint: "下位ページ用．サイドバーでの表示順．"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "online-worship" # Used in routes, e.g., /admin/collections/blog
    label: "オンラインで聞ける賛美やワーシップ" # Used in the UI
    folder: "content/worship-songs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}_{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: worship-songs/{{slug}}
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
